-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglvluSYohRKnUBFfH
8BktEL8UGepIP+1NU7bZuIQ5DJ+gCgYIKoZIzj0DAQehRANCAARfQwoUyiS7H4xx
tdM1p31L9ND4IhAP47LZCEWr79PwoCjlyPxR0qc0DBymscRlOqLywRFpL+H1DKXH
INPqkIrE
-----END PRIVATE KEY-----